# Generated by Django 3.2.8 on 2022-03-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220330_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='incomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment'),
        ),
    ]
