# Generated by Django 3.2.8 on 2022-04-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_incomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Maqola', 'verbose_name_plural': 'Maqolalar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='article',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default="Text yo'q", max_length=8000, verbose_name='MAQOLA Matni'),
        ),
        migrations.AlterField(
            model_name='article',
            name='view',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='category',
            name='article_qty',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
